# Generated by Django 5.2.1 on 2025-05-24 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='secret_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
