# Generated by Django 5.2.1 on 2025-05-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_signup_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='secret_key',
            field=models.CharField(max_length=200),
        ),
    ]
